Sourcecode/GenericPayment/Controllers/NganLuongController.cs
using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Net.Http;
using System.Threading.Tasks;
using System.Web.Mvc;
using GenericPayment.Database;
using GenericPayment.Models;
using GenericPayment.Utilities;
using Newtonsoft.Json;

namespace GenericPayment.Controllers
{
    public enum ReturnType
    {
        Success = 0,
        Cancel = 1,
        Timeout = 2
    }

    [Serializable]
    public class SearchCriteria
    {
        public string invoiceno { get; set; }
        public string paykey { get; set; }
        public string providertransref { get; set; }
        public string fromdate { get; set; }
        public string todate { get; set; }
    }

    public class NganLuongController : Controller
    {
        public async Task<ActionResult> Index(string paykey, bool reload = false)
        {
            var marketplaceUrl = GetMarketPlaceUrl();
            var db = new DbContext();
            try
            {
                var details = db.GetDetails(paykey);
                if (details != null)
                {
                    // Update details for the valid record
                    var vm = new PaymentDetails();
                    vm.CashKey = details.PayKey;
                    vm.Currency = details.Currency;

                    decimal total;
                    if (!decimal.TryParse(details.Total, out total))
                    {
                        total = 0m;
                    }
                    vm.Total = total;

                    if (!reload)
                    {
                        using (var httpClient = new HttpClient())
                        {
                            var url = marketplaceUrl + "/user/checkout/order-details" + "?gateway=" + details.Gateway + "&invoiceNo=" + details.InvoiceNo + "&paykey=" + paykey + "&hashkey=" + details.Hashkey;
                            HttpResponseMessage tokenResponse = await httpClient.GetAsync(url);
                            tokenResponse.EnsureSuccessStatusCode();
                            string text = await tokenResponse.Content.ReadAsStringAsync();

                            // Set the details to db
                            var response = JsonConvert.DeserializeObject<GenericPayments>(text);
                            details.PayeeInfos = response.PayeeInfos;
                            details.MarketplaceUrl = marketplaceUrl;
                            db.SetDetails(paykey, details);
                        }
                    }

                    return View("Index", vm);
                }
            }
            catch (Exception ex)
            {
                ViewBag.ErrorMessage = ex.Message;
                Logger.GetInstance().Write(ex, string.Format("[Key={0}]Exception thrown in NganLuongController.Index", paykey));
            }

            return View("Error");
        }

        private string GetMarketPlaceUrl()
        {
            var marketplaceUrl = ConfigCode.GetInstance().MarketPlaceUrl;

            if (Request.UrlReferrer != null)
            {
                marketplaceUrl = Request.UrlReferrer.ToString();
            }

            var uri = new Uri(marketplaceUrl);
            marketplaceUrl = uri.Scheme + Uri.SchemeDelimiter + uri.Authority;

            return marketplaceUrl;
        }

        public JsonResult AgreeToPay(AgreementViewModel vm)
        {
            string redirectUrl = "";
            string errorMessage = "";
            var db = new DbContext();

            try
            {
                //DEBUG
                //Logger.GetInstance().Write(JsonConvert.SerializeObject(vm));

                var details = db.GetDetails(vm.CashKey);
                if (details != null)
                {
                    details.AgreedDateTime = DateTime.UtcNow;

                    var info = new RequestInfo();
                    info.Merchant_id = ConfigCode.GetInstance().MerchantID;
                    info.Merchant_password = ConfigCode.GetInstance().MerchantPassword;
                    info.Receiver_email = ConfigCode.GetInstance().ReceiverEmail;

                    info.cur_code = "vnd";
                    info.Payment_method = vm.OptionPayment;
                    info.bank_code = vm.BankCode;
                    info.Order_code = details.InvoiceNo;
                    info.Total_amount = details.Total;
                    info.Buyer_fullname = vm.FullName;
                    info.Buyer_email = vm.Email;
                    info.Buyer_mobile = vm.Phone;

                    //Optional fields
                    info.fee_shipping = "0";
                    info.Discount_amount = "0";
                    info.order_description = "";
                    // End of optional fields

                    string host = HttpContext.Request.Url.Scheme + "://" + HttpContext.Request.Url.Authority;
                    string baseUrl = string.Format("{0}/nganluong/return?", host);
                    info.return_url = baseUrl + "key=" + vm.CashKey;
                    info.cancel_url = baseUrl + "key=" + vm.CashKey + "&type=" + ReturnType.Cancel.GetHashCode();
                    info.time_limit = baseUrl + "key=" + vm.CashKey + "&type=" + ReturnType.Timeout.GetHashCode();

                    //DEBUG
                    //Logger.GetInstance().Write("RequestInfo");
                    //Logger.GetInstance().Write(JsonConvert.SerializeObject(info));

                    var objApiCheckout = new APICheckoutV3();
                    ResponseInfo checkoutRs = objApiCheckout.GetUrlCheckout(info, vm.OptionPayment);

                    //DEBUG
                    //Logger.GetInstance().Write("Check out response:");
                    //Logger.GetInstance().Write(JsonConvert.SerializeObject(checkoutRs));

                    if (checkoutRs.Error_code == "00")
                    {
                        details.ProviderTransRefId = checkoutRs.Token;
                        bool result = db.SetDetails(vm.CashKey, details);
                        if (result)
                        {
                            redirectUrl = checkoutRs.Checkout_url;
                        }
                        else
                        {
                            errorMessage = Resources.Application.CommonErrorMessage;
                            Logger.GetInstance().Write(string.Format("[Key={0}] Check out succeeded but failed to update NL Token", vm.CashKey));
                        }
                    }
                    else
                    {
                        ;
                        errorMessage = string.Format("Error Description: {0}. <br/> {1}", checkoutRs.Description, Resources.Application.CommonErrorMessage);
                        Logger.GetInstance().Write(string.Format("[Key={0}] Failed to check out(Code={1};Desc={2})", vm.CashKey, checkoutRs.Error_code, checkoutRs.Description));
                    }
                }
            }
            catch (Exception ex)
            {
                Logger.GetInstance().Write(ex, string.Format("[Key={0}]Exception thrown in AgreeToPay", vm.CashKey));
                ViewBag.ErrorMessage = ex.Message;
                redirectUrl = "";
            }

            // Use js to redirect to NL check out URL.
            return Json(new { result = redirectUrl, message = errorMessage }, JsonRequestBehavior.AllowGet);
        }

        public JsonResult CancelToPay(AgreementViewModel vm)
        {
            var url = DbContext.CancelUrl(vm.CashKey);
            return Json(new { result = url }, JsonRequestBehavior.AllowGet);
        }

        /// <summary>
        /// NganLuong will return to this endpoint.
        /// </summary>
        /// <param name="token">return token if success</param>
        /// <param name="key"></param>
        /// <param name="type">0: success; 1: cancel; 2: timeout</param>
        /// <returns></returns>
        [ActionName("return")]
        public ActionResult PaymentReturn(string token, string key, int type = 0)
        {
            string result;

            //DEBUG
            //Logger.GetInstance().Write("Payment Return URL:");
            //Logger.GetInstance().Write(Request.Url.AbsoluteUri.ToString());

            if (type == ReturnType.Cancel.GetHashCode() || type == ReturnType.Timeout.GetHashCode() ||
                string.IsNullOrEmpty(key) || string.IsNullOrEmpty(token))
            {
                result = DbContext.CancelUrl(key);
                return Redirect(result);
            }

            var db = new DbContext();
            var details = db.GetDetails(key);
            if (details != null && details.ProviderTransRefId == token)
            {
                var info = new RequestCheckOrder();
                info.Merchant_id = ConfigCode.GetInstance().MerchantID;
                info.Merchant_password = ConfigCode.GetInstance().MerchantPassword;
                info.Token = token;
                var objApiCheckout = new APICheckoutV3();
                ResponseCheckOrder checkOrderRs = objApiCheckout.GetTransactionDetail(info);

                //DEBUG
                //Logger.GetInstance().Write("Transaction details:");
                // Logger.GetInstance().Write(JsonConvert.SerializeObject(checkOrderRs));

                switch (checkOrderRs.transactionStatus)
                {
                    case "00":
                        details.PaymentStatus = EnumPaymentStatus.Paid.GetHashCode();
                        break;
                    case "01":
                        details.PaymentStatus = EnumPaymentStatus.Pending.GetHashCode();
                        break;
                    case "02":
                        details.PaymentStatus = EnumPaymentStatus.Unpaid.GetHashCode();
                        break;
                }

                var updateRs = db.SetDetails(key, details);

Sourcecode/GenericPayment/Views/NganLuong/Admin.cshtml
@{
    ViewBag.Title = "Payment Transaction History";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

@section headercss
{
    <!-- Include Bootstrap Datepicker -->
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.3.0/css/datepicker.min.css" />
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.3.0/css/datepicker3.min.css" />
}

<div class="container">
    <div class="container">
        <div class="row well content-width">
            <div class="container">
                <div class="form-group row">
                    <div class="col-xs-2">
                        <label for="invoiceno">Invoice Number:</label>
                        <input type="text" class="form-control" placeholder="Invoice Number" id="invoiceno">
                    </div>
                    <div class="col-xs-2">
                        <label for="paykey">Paykey:</label>
                        <input type="text" class="form-control" placeholder="Paykey" id="paykey">
                    </div>
                    <div class="col-xs-2">
                        <label for="providertransref">Provider TransRef:</label>
                        <input type="text" class="form-control" placeholder="Provider TransRef" id="providertransref">
                    </div>
                    <div class="col-xs-2">
                        <label for="fromdate">From Date:</label>
                        <div class="input-group input-append date" id="fromDatePicker">
                            <input type="text" class="form-control" placeholder="From Date" id="fromdate">
                            <span class="input-group-addon add-on"><span class="glyphicon glyphicon-calendar"></span></span>
                        </div>
                    </div>
                    <div class="col-xs-2">
                        <label for="todate">To Date:</label>
                        <div class="input-group input-append date" id="toDatePicker">
                            <input type="text" class="form-control" placeholder="To Date" id="todate">
                            <span class="input-group-addon add-on"><span class="glyphicon glyphicon-calendar"></span></span>
                        </div>
                    </div>
                    <div class="col-xs-2">
                        <label for="btnSearch">&nbsp;</label>
                        <div class="">
                            <button type="submit" id="btnSearch" class="btn btn-primary">Search</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div id="searchResult" class="row text-center">
        </div>
    </div>
</div>
<input type="hidden" id="searchUrl" value="@Url.Action("Search", "NganLuong")" />
@section scripts {
    <script src="//cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.3.0/js/bootstrap-datepicker.min.js"></script>
    <script src="~/assets/js/nl-admin.js"></script>

}

Sourcecode/GenericPayment/Views/NganLuong/Index.cshtml
@model GenericPayment.Models.PaymentDetails

@{
    ViewBag.Title = "Index";
}

<div class="container">
    <div class="container content-width">
        <div class="row" style="margin-top:10px">
            <p>@Html.Raw(Resources.Application.PaymentGatewayDescription)</p>
        </div>
        <div class="row">
            <p>@Resources.Application.PleaseChoosePaymentMethod</p>
        </div>
        <div class="row">
            <div class="panel-group">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <label>
                            <input id="optionNL" name="option_payment" value="NL" type="radio" checked="" />
                            @Resources.Application.PaybyNLWallet
                        </label>
                    </div>
                    <div class="panel-body">
                        <p>
                            <i>@Html.Raw(Resources.Application.PaybyNLWalletDescription)</i>
                        </p>
                    </div>
                </div>
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <label>
                            <input id="optionATMOnline" name="option_payment" value="ATM_ONLINE" type="radio" />
                            @Resources.Application.PaybyATMOnline
                        </label>
                    </div>
                    <div class="panel-body">
                        <p>
                            <i>
                                <span style="color:#ff5a00;font-weight:bold;text-decoration:underline;">@Resources.Application.Attention</span>: @Html.Raw(Resources.Application.PaybyATMOnlineNote)
                            </i>
                        </p>
                        <ul class="cardList clearfix">

                            <li class="bank-online-methods ">
                                <label for="vcb_ck_on">
                                    <i class="VCB" title="Ngân hàng TMCP Ngoại Thương Việt Nam"></i>
                                    <input id="optVCB" name="bankcode" type="radio" value="VCB" />
                                </label>
                            </li>

                            <li class="bank-online-methods ">
                                <label for="vnbc_ck_on">
                                    <i class="DAB" title="Ngân hàng Đông Á"></i>
                                    <input id="optDAB" name="bankcode" type="radio" value="DAB" />
                                </label>
                            </li>

                            <li class="bank-online-methods ">
                                <label for="tcb_ck_on">
                                    <i class="TCB" title="Ngân hàng Kỹ Thương"></i>
                                    <input id="optTCB" name="bankcode" type="radio" value="TCB" />
                                </label>
                            </li>

                            <li class="bank-online-methods ">
                                <label for="sml_atm_mb_ck_on">
                                    <i class="MB" title="Ngân hàng Quân Đội"></i>
                                    <input id="optMB" name="bankcode" type="radio" value="MB" />
                                </label>
                            </li>

                            <li class="bank-online-methods ">
                                <label for="shb_ck_on">
                                    <i class="SHB" title="Ngân hàng Sài Gòn - Hà Nội"></i>
                                    <input id="optSHB" name="bankcode" type="radio" value="SHB" />
                                </label>
                            </li>

                            <li class="bank-online-methods ">
                                <label for="sml_atm_vib_ck_on">
                                    <i class="VIB" title="Ngân hàng Quốc tế"></i>
                                    <input id="optVIB" name="bankcode" type="radio" value="VIB" />

                                </label>
                            </li>

                            <li class="bank-online-methods ">
                                <label for="sml_atm_vtb_ck_on">
                                    <i class="ICB" title="Ngân hàng Công Thương Việt Nam"></i>
                                    <input id="optICB" name="bankcode" type="radio" value="ICB" />

                                </label>
                            </li>

                            <li class="bank-online-methods ">
                                <label for="sml_atm_exb_ck_on">
                                    <i class="EXB" title="Ngân hàng Xuất Nhập Khẩu"></i>
                                    <input id="optEXB" name="bankcode" type="radio" value="EXB" />

                                </label>
                            </li>

                            <li class="bank-online-methods ">
                                <label for="sml_atm_acb_ck_on">
                                    <i class="ACB" title="Ngân hàng Á Châu"></i>
                                    <input id="optACB" name="bankcode" type="radio" value="ACB" />

                                </label>
                            </li>

                            <li class="bank-online-methods ">
                                <label for="sml_atm_hdb_ck_on">
                                    <i class="HDB" title="Ngân hàng Phát triển Nhà TPHCM"></i>
                                    <input id="optHDB" name="bankcode" type="radio" value="HDB" />

                                </label>
                            </li>

                            <li class="bank-online-methods ">
                                <label for="sml_atm_msb_ck_on">
                                    <i class="MSB" title="Ngân hàng Hàng Hải"></i>
                                    <input id="optMSB" name="bankcode" type="radio" value="MSB" />

                                </label>
                            </li>

                            <li class="bank-online-methods ">
                                <label for="sml_atm_nvb_ck_on">
                                    <i class="NVB" title="Ngân hàng Nam Việt"></i>
                                    <input id="optNVB" name="bankcode" type="radio" value="NVB" />

                                </label>
                            </li>

                            <li class="bank-online-methods ">
                                <label for="sml_atm_vab_ck_on">
                                    <i class="VAB" title="Ngân hàng Việt Á"></i>
                                    <input id="optVAB" name="bankcode" type="radio" value="VAB" />

                                </label>
                            </li>

                            <li class="bank-online-methods ">
                                <label for="sml_atm_vpb_ck_on">
                                    <i class="VPB" title="Ngân Hàng Việt Nam Thịnh Vượng"></i>
                                    <input id="optVPB" name="bankcode" type="radio" value="VPB" />

                                </label>
                            </li>

                            <li class="bank-online-methods ">
                                <label for="sml_atm_scb_ck_on">
                                    <i class="SCB" title="Ngân hàng Sài Gòn Thương tín"></i>
                                    <input id="optSCB" name="bankcode" type="radio" value="SCB" />

                                </label>
                            </li>

                            <li class="bank-online-methods ">
                                <label for="ojb_ck_on">
                                    <i class="OJB" title="Ngân hàng Đại Dương"></i>
                                    <input id="optOJB" name="bankcode" type="radio" value="OJB" />

                                </label>
                            </li>

                            <li class="bank-online-methods ">
                                <label for="bnt_atm_pgb_ck_on">
                                    <i class="PGB" title="Ngân hàng Xăng dầu Petrolimex"></i>
                                    <input id="optPGB" name="bankcode" type="radio" value="PGB" />

                                </label>
                            </li>

                            <li class="bank-online-methods ">
                                <label for="bnt_atm_gpb_ck_on">
                                    <i class="GPB" title="Ngân hàng TMCP Dầu khí Toàn Cầu"></i>
                                    <input id="optGPB" name="bankcode" type="radio" value="GPB" />

                                </label>
                            </li>

                            <li class="bank-online-methods ">
                                <label for="bnt_atm_agb_ck_on">
                                    <i class="AGB" title="Ngân hàng Nông nghiệp &amp; Phát triển nông thôn"></i>
                                    <input id="optAGB" name="bankcode" type="radio" value="AGB" />

                                </label>
                            </li>

                            <li class="bank-online-methods ">
                                <label for="bnt_atm_sgb_ck_on">
                                    <i class="SGB" title="Ngân hàng Sài Gòn Công Thương"></i>
                                    <input id="optSGB" name="bankcode" type="radio" value="SGB" />

                                </label>
                            </li>

                            <li class="bank-online-methods ">
                                <label for="bnt_atm_nab_ck_on">
                                    <i class="NAB" title="Ngân hàng Nam Á"></i>
                                    <input id="optNAB" name="bankcode" type="radio" value="NAB" />

                                </label>
                            </li>

                            <li class="bank-online-methods ">
                                <label for="sml_atm_bab_ck_on">
                                    <i class="BAB" title="Ngân hàng Bắc Á"></i>
                                    <input id="optBAB" name="bankcode" type="radio" value="BAB" />

                                </label>
                            </li>

                        </ul>
                    </div>
                </div>
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <label>
                            <input id="optionCredit" name="option_payment" value="VISA" type="radio" />
                            @Resources.Application.PaybyCreditCard
                        </label>
                    </div>

                </div>
            </div>
        </div>
        <div class="row">
            <p class="">@Resources.Application.PleaseEnterFollowingInformation</p>

            <div class="input-group">
                <span class="input-group-addon"><i class="glyphicon glyphicon-user"></i></span>
                <input id="txtFullName" type="text" class="form-control" name="txtFullName" placeholder="@Resources.Application.FullName">
            </div>
            <div class="input-group">
                <span class="input-group-addon"><i class="glyphicon glyphicon-envelope"></i></span>
                <input id="txtEmail" type="text" class="form-control" name="txtEmail" placeholder="@Resources.Application.Email">
            </div>
            <div class="input-group">
                <span class="input-group-addon"><i class="glyphicon glyphicon-phone"></i></span>
                <input id="txtPhone" type="text" class="form-control" name="txtPhone" placeholder="@Resources.Application.PhoneNumber">
            </div>

            <div id="divError" class="alert alert-danger hide" style="margin-top: 10px"> </div>
            <div style="margin-top: 5px">
                <input type="hidden" value="@Url.Action("AgreeToPay", "NganLuong")" id="agreeUrl" />
                <input type="hidden" value="@Url.Action("CancelToPay", "NganLuong")" id="cancelUrl" />
                <input type="hidden" value="@Model.CashKey" id="cashkey" />
                <input type="hidden" value="@Resources.Application.BuyerDetailMandatory" id="BuyerDetailMandatory" />
                <input type="hidden" value="@Resources.Application.DomesticBankMandatory" id="DomesticBankMandatory" />

                <input class="btn btn-primary" type="submit" id="agree" value="@Resources.Application.ProceedPayment">
                <input class="btn btn-default" type="submit" id="cancel" value="@Resources.Application.CancelPayment">
            </div>
        </div>
    </div>
</div>

@section scripts {
    <script src="~/assets/js/nl-checkout.js"></script>
}

Sourcecode/GenericPayment/Views/NganLuong/SearchResult.cshtml
@using GenericPayment.Models
@model GenericPayment.Models.AdminModel


<table class="table table-bordered table-striped table-hover" style="width: 95%">
    <thead>
    <th>#</th>
    <th>Invoice No.</th>
    <th>PayKey</th>
    <th>Amount</th>
    <th>Provider TransRefID</th>
    <th>Agreed DateTime</th>
    <th>Status</th>
    <th>Raw Data</th>
    </thead>
    <tbody>
        @if (Model.PaymentItems != null && Model.PaymentItems.Any())
            {
                var index = 0;
                foreach (var paymentItem in Model.PaymentItems)
                {
                    index++;
                    var status = (EnumPaymentStatus)paymentItem.Payment.PaymentStatus;
                    var agreedDt = paymentItem.FileInformation.CreationTime.ToString("dd-MMM-yyyy hh:mm:ss");
                    if (paymentItem.Payment.AgreedDateTime.HasValue && paymentItem.Payment.AgreedDateTime.Value != DateTime.MinValue)
                    {
                        agreedDt = paymentItem.Payment.AgreedDateTime.Value.ToString("dd-MMM-yyyy hh:mm:ss");
                    }

            <tr>
                <td>@index.ToString()</td>
                <td>@paymentItem.Payment.InvoiceNo</td>
                <td>@paymentItem.Payment.PayKey</td>
                <td class="text-right">@paymentItem.Payment.Total</td>
                <td>@paymentItem.Payment.ProviderTransRefId</td>
                <td>@agreedDt</td>
                <td class="text-right">@status.ToString()</td>
                <td class="text-center"><a href="#" data-toggle="modal" data-target="#myModal" onclick="viewRawData(@paymentItem.RawData)">View</a></td>
            </tr>
                }
            }
            else
            {
            <tr>
                <td colspan="8">No data found.</td>
            </tr>
            }

    </tbody>
</table>
<ul class="pager">
    <li><a href="#">Previous</a></li>
    <li><a href="#">Next</a></li>
</ul>